
# This file is automatically generated, you probably don't want to edit this

paretoOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "paretoOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            counts = NULL, ...) {

            super$initialize(
                package='scatr',
                name='pareto',
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "nominal",
                    "nominaltext",
                    "ordinal"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                default=NULL,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"))

            self$.addOption(private$..x)
            self$.addOption(private$..counts)
        }),
    active = list(
        x = function() private$..x$value,
        counts = function() private$..counts$value),
    private = list(
        ..x = NA,
        ..counts = NA)
)

paretoResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        pareto = function() private$.items[["pareto"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Pareto Chart")
            self$add(jmvcore::Image$new(
                options=options,
                name="pareto",
                title="",
                renderFun=".pareto",
                clearWith=list(
                    "x",
                    "counts")))}))

paretoBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "paretoBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'scatr',
                name = 'pareto',
                version = c(1,0,0),
                options = options,
                results = paretoResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Pareto Chart
#'
#' Function for making pareto charts.
#'
#' @examples
#' set.seed(1337)
#'
#' X <- sample(c('A','B','C','D','E','F'), 100, replace=TRUE)
#' dat <- data.frame(X = X)
#'
#' pareto(dat, x = 'X')
#'
#' @param data the data as a data frame
#' @param x a string naming the variable from \code{data} that contains the
#'   values used for the chart
#' @param counts a string naming the variable from \code{data} that contains
#'   the  counts for the values (optional)
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$pareto} \tab \tab \tab \tab \tab a Pareto chart \cr
#' }
#'
#' @export
pareto <- function(
    data,
    x,
    counts = NULL) {

    if ( ! requireNamespace('jmvcore'))
        stop('pareto requires jmvcore to be installed (restart may be required)')

    options <- paretoOptions$new(
        x = x,
        counts = counts)

    results <- paretoResults$new(
        options = options)

    analysis <- paretoClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
