
# This file is automatically generated, you probably don't want to edit this

scatOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "scatOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            y = NULL,
            group = NULL,
            marg = "none",
            line = FALSE,
            se = FALSE, ...) {

            super$initialize(
                package='scatr',
                name='scat',
                requiresData=TRUE,
                ...)
        
            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"))
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "nominal",
                    "nominaltext",
                    "ordinal"))
            private$..marg <- jmvcore::OptionList$new(
                "marg",
                marg,
                options=list(
                    "none",
                    "dens",
                    "box"),
                default="none")
            private$..line <- jmvcore::OptionBool$new(
                "line",
                line,
                default=FALSE)
            private$..se <- jmvcore::OptionBool$new(
                "se",
                se,
                default=FALSE)
        
            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..group)
            self$.addOption(private$..marg)
            self$.addOption(private$..line)
            self$.addOption(private$..se)
        }),
    active = list(
        x = function() private$..x$value,
        y = function() private$..y$value,
        group = function() private$..group$value,
        marg = function() private$..marg$value,
        line = function() private$..line$value,
        se = function() private$..se$value),
    private = list(
        ..x = NA,
        ..y = NA,
        ..group = NA,
        ..marg = NA,
        ..line = NA,
        ..se = NA)
)

scatResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        scat = function() private$..scat),
    private = list(
        ..scat = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Scatterplot")
            private$..scat <- jmvcore::Image$new(
                options=options,
                name="scat",
                title="",
                width=650,
                height=500,
                renderFun=".scat",
                clearWith=list(
                    "x",
                    "y",
                    "group",
                    "marg",
                    "line",
                    "se"))
            self$add(private$..scat)}))

scatBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "scatBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'scatr',
                name = 'scat',
                version = c(1,0,0),
                options = options,
                results = scatResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Scatterplot
#'
#' 
#' @param data .
#' @param x .
#' @param y .
#' @param group .
#' @param marg \code{TRUE} or \code{FALSE} (default), provide density plots on 
#'   both axes 
#' @param line \code{TRUE} or \code{FALSE} (default), add regression line to 
#'   plot 
#' @param se \code{TRUE} or \code{FALSE} (default), add standard error for the 
#'   regression line 
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$scat} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
scat <- function(
    data,
    x,
    y,
    group,
    marg = "none",
    line = FALSE,
    se = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('scat requires jmvcore to be installed (restart may be required)')

    options <- scatOptions$new(
        x = x,
        y = y,
        group = group,
        marg = marg,
        line = line,
        se = se)

    results <- scatResults$new(
        options = options)

    analysis <- scatClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
