
# This file is automatically generated, you probably don't want to edit this

scatOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            y = NULL,
            group = NULL,
            marg = "none",
            line = "none",
            se = FALSE,
            xRangeAuto = TRUE,
            xmin = 0,
            xmax = 10,
            xBreaksAuto = TRUE,
            xNBreaks = 5,
            yRangeAuto = TRUE,
            ymin = 0,
            ymax = 10,
            yBreaksAuto = TRUE,
            yNBreaks = 5, ...) {

            super$initialize(
                package="scatr",
                name="scat",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..marg <- jmvcore::OptionList$new(
                "marg",
                marg,
                options=list(
                    "none",
                    "dens",
                    "box"),
                default="none")
            private$..line <- jmvcore::OptionList$new(
                "line",
                line,
                options=list(
                    "none",
                    "linear",
                    "smooth"),
                default="none")
            private$..se <- jmvcore::OptionBool$new(
                "se",
                se,
                default=FALSE)
            private$..xRangeAuto <- jmvcore::OptionBool$new(
                "xRangeAuto",
                xRangeAuto,
                default=TRUE)
            private$..xmin <- jmvcore::OptionNumber$new(
                "xmin",
                xmin,
                default=0)
            private$..xmax <- jmvcore::OptionNumber$new(
                "xmax",
                xmax,
                default=10)
            private$..xBreaksAuto <- jmvcore::OptionBool$new(
                "xBreaksAuto",
                xBreaksAuto,
                default=TRUE)
            private$..xNBreaks <- jmvcore::OptionNumber$new(
                "xNBreaks",
                xNBreaks,
                default=5,
                min=2)
            private$..yRangeAuto <- jmvcore::OptionBool$new(
                "yRangeAuto",
                yRangeAuto,
                default=TRUE)
            private$..ymin <- jmvcore::OptionNumber$new(
                "ymin",
                ymin,
                default=0)
            private$..ymax <- jmvcore::OptionNumber$new(
                "ymax",
                ymax,
                default=10)
            private$..yBreaksAuto <- jmvcore::OptionBool$new(
                "yBreaksAuto",
                yBreaksAuto,
                default=TRUE)
            private$..yNBreaks <- jmvcore::OptionNumber$new(
                "yNBreaks",
                yNBreaks,
                default=5,
                min=2)

            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..group)
            self$.addOption(private$..marg)
            self$.addOption(private$..line)
            self$.addOption(private$..se)
            self$.addOption(private$..xRangeAuto)
            self$.addOption(private$..xmin)
            self$.addOption(private$..xmax)
            self$.addOption(private$..xBreaksAuto)
            self$.addOption(private$..xNBreaks)
            self$.addOption(private$..yRangeAuto)
            self$.addOption(private$..ymin)
            self$.addOption(private$..ymax)
            self$.addOption(private$..yBreaksAuto)
            self$.addOption(private$..yNBreaks)
        }),
    active = list(
        x = function() private$..x$value,
        y = function() private$..y$value,
        group = function() private$..group$value,
        marg = function() private$..marg$value,
        line = function() private$..line$value,
        se = function() private$..se$value,
        xRangeAuto = function() private$..xRangeAuto$value,
        xmin = function() private$..xmin$value,
        xmax = function() private$..xmax$value,
        xBreaksAuto = function() private$..xBreaksAuto$value,
        xNBreaks = function() private$..xNBreaks$value,
        yRangeAuto = function() private$..yRangeAuto$value,
        ymin = function() private$..ymin$value,
        ymax = function() private$..ymax$value,
        yBreaksAuto = function() private$..yBreaksAuto$value,
        yNBreaks = function() private$..yNBreaks$value),
    private = list(
        ..x = NA,
        ..y = NA,
        ..group = NA,
        ..marg = NA,
        ..line = NA,
        ..se = NA,
        ..xRangeAuto = NA,
        ..xmin = NA,
        ..xmax = NA,
        ..xBreaksAuto = NA,
        ..xNBreaks = NA,
        ..yRangeAuto = NA,
        ..ymin = NA,
        ..ymax = NA,
        ..yBreaksAuto = NA,
        ..yNBreaks = NA)
)

scatResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatResults",
    inherit = jmvcore::Group,
    active = list(
        scat = function() private$.items[["scat"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Scatterplot")
            self$add(jmvcore::Image$new(
                options=options,
                name="scat",
                title="",
                renderFun=".scat",
                requiresData=TRUE))}))

scatBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "scatr",
                name = "scat",
                version = c(1,0,0),
                options = options,
                results = scatResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Scatterplot
#'
#' Function for making clean, good looking scatter plots with the option to 
#' add marginal denisty or box plots.
#'
#' @examples
#' set.seed(1337)
#'
#' X <- rnorm(100)
#' Y <- 0.5*X + rnorm(100)
#' dat <- data.frame(X = X, Y = Y)
#'
#' scat(dat, x = 'X', y = 'Y', line = 'linear', se = TRUE, marg = 'dens')
#'
#' @param data the data as a data frame
#' @param x a string naming the variable from \code{data} that contains the  x
#'   coordinates of the points in the plot, variable must be numeric
#' @param y a string naming the variable from \code{data} that contains the  y
#'   coordinates of the points in the plot, variable must be numeric
#' @param group a string naming the variable from \code{data} that represents
#'   the  grouping variable
#' @param marg \code{none} (default), \code{dens}, or \code{box}, provide
#'   respectively no plots, density plots, or box plots on the axes
#' @param line \code{none} (default), \code{linear}, or \code{smooth}, provide
#'   respectively no regression line,  a linear regression line, or a smoothed
#'   regression line
#' @param se \code{TRUE} or \code{FALSE} (default), show the standard error
#'   for the regression line
#' @param xRangeAuto \code{TRUE} (default) or \code{FALSE} , automatically
#'   determine the range for  the x-axis
#' @param xmin a number defining the minimum of the scale for the x-axis
#' @param xmax a number defining the maximum of the scale for the x-axis
#' @param xBreaksAuto \code{TRUE} (default) or \code{FALSE} , automatically
#'   determine the number of  breaks for the ticks on the x-axis
#' @param xNBreaks a number defining the number of ticks breaks for the x-axis
#' @param yRangeAuto \code{TRUE} (default) or \code{FALSE} , automatically
#'   determine the range for  the y-axis
#' @param ymin a number defining the minimum of the scale for the y-axis
#' @param ymax a number defining the maximum of the scale for the y-axis
#' @param yBreaksAuto \code{TRUE} (default) or \code{FALSE} , automatically
#'   determine the number of  breaks for the ticks on the y-axis
#' @param yNBreaks a number defining the number of ticks breaks for the y-axis
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$scat} \tab \tab \tab \tab \tab a scatter plot \cr
#' }
#'
#' @export
scat <- function(
    data,
    x,
    y,
    group = NULL,
    marg = "none",
    line = "none",
    se = FALSE,
    xRangeAuto = TRUE,
    xmin = 0,
    xmax = 10,
    xBreaksAuto = TRUE,
    xNBreaks = 5,
    yRangeAuto = TRUE,
    ymin = 0,
    ymax = 10,
    yBreaksAuto = TRUE,
    yNBreaks = 5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("scat requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- scatOptions$new(
        x = x,
        y = y,
        group = group,
        marg = marg,
        line = line,
        se = se,
        xRangeAuto = xRangeAuto,
        xmin = xmin,
        xmax = xmax,
        xBreaksAuto = xBreaksAuto,
        xNBreaks = xNBreaks,
        yRangeAuto = yRangeAuto,
        ymin = ymin,
        ymax = ymax,
        yBreaksAuto = yBreaksAuto,
        yNBreaks = yNBreaks)

    analysis <- scatClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

