
# This file is automatically generated, you probably don't want to edit this

scatOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            y = NULL,
            group = NULL,
            marg = "none",
            line = "none",
            se = FALSE,
            xmin = NULL,
            xmax = NULL,
            xNBreaks = NULL,
            xTitle = "",
            xTitleAlign = "auto",
            xLabelsAngle = NULL,
            ymin = NULL,
            ymax = NULL,
            yNBreaks = NULL,
            yTitle = "",
            yTitleAlign = "auto", ...) {

            super$initialize(
                package="scatr",
                name="scat",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..marg <- jmvcore::OptionList$new(
                "marg",
                marg,
                options=list(
                    "none",
                    "dens",
                    "box"),
                default="none")
            private$..line <- jmvcore::OptionList$new(
                "line",
                line,
                options=list(
                    "none",
                    "linear",
                    "smooth"),
                default="none")
            private$..se <- jmvcore::OptionBool$new(
                "se",
                se,
                default=FALSE)
            private$..xmin <- jmvcore::OptionNumber$new(
                "xmin",
                xmin,
                default=NULL)
            private$..xmax <- jmvcore::OptionNumber$new(
                "xmax",
                xmax,
                default=NULL)
            private$..xNBreaks <- jmvcore::OptionInteger$new(
                "xNBreaks",
                xNBreaks,
                default=NULL,
                min=2)
            private$..xTitle <- jmvcore::OptionString$new(
                "xTitle",
                xTitle,
                default="")
            private$..xTitleAlign <- jmvcore::OptionList$new(
                "xTitleAlign",
                xTitleAlign,
                options=list(
                    "auto",
                    "left",
                    "middle",
                    "right"),
                default="auto")
            private$..xLabelsAngle <- jmvcore::OptionNumber$new(
                "xLabelsAngle",
                xLabelsAngle,
                min=0,
                max=90,
                default=NULL)
            private$..ymin <- jmvcore::OptionNumber$new(
                "ymin",
                ymin,
                default=NULL)
            private$..ymax <- jmvcore::OptionNumber$new(
                "ymax",
                ymax,
                default=NULL)
            private$..yNBreaks <- jmvcore::OptionInteger$new(
                "yNBreaks",
                yNBreaks,
                default=NULL,
                min=2)
            private$..yTitle <- jmvcore::OptionString$new(
                "yTitle",
                yTitle,
                default="")
            private$..yTitleAlign <- jmvcore::OptionList$new(
                "yTitleAlign",
                yTitleAlign,
                options=list(
                    "auto",
                    "top",
                    "middle",
                    "bottom"),
                default="auto")

            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..group)
            self$.addOption(private$..marg)
            self$.addOption(private$..line)
            self$.addOption(private$..se)
            self$.addOption(private$..xmin)
            self$.addOption(private$..xmax)
            self$.addOption(private$..xNBreaks)
            self$.addOption(private$..xTitle)
            self$.addOption(private$..xTitleAlign)
            self$.addOption(private$..xLabelsAngle)
            self$.addOption(private$..ymin)
            self$.addOption(private$..ymax)
            self$.addOption(private$..yNBreaks)
            self$.addOption(private$..yTitle)
            self$.addOption(private$..yTitleAlign)
        }),
    active = list(
        x = function() private$..x$value,
        y = function() private$..y$value,
        group = function() private$..group$value,
        marg = function() private$..marg$value,
        line = function() private$..line$value,
        se = function() private$..se$value,
        xmin = function() private$..xmin$value,
        xmax = function() private$..xmax$value,
        xNBreaks = function() private$..xNBreaks$value,
        xTitle = function() private$..xTitle$value,
        xTitleAlign = function() private$..xTitleAlign$value,
        xLabelsAngle = function() private$..xLabelsAngle$value,
        ymin = function() private$..ymin$value,
        ymax = function() private$..ymax$value,
        yNBreaks = function() private$..yNBreaks$value,
        yTitle = function() private$..yTitle$value,
        yTitleAlign = function() private$..yTitleAlign$value),
    private = list(
        ..x = NA,
        ..y = NA,
        ..group = NA,
        ..marg = NA,
        ..line = NA,
        ..se = NA,
        ..xmin = NA,
        ..xmax = NA,
        ..xNBreaks = NA,
        ..xTitle = NA,
        ..xTitleAlign = NA,
        ..xLabelsAngle = NA,
        ..ymin = NA,
        ..ymax = NA,
        ..yNBreaks = NA,
        ..yTitle = NA,
        ..yTitleAlign = NA)
)

scatResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatResults",
    inherit = jmvcore::Group,
    active = list(
        scat = function() private$.items[["scat"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Scatterplot")
            self$add(jmvcore::Image$new(
                options=options,
                name="scat",
                title="",
                renderFun=".scat",
                requiresData=TRUE))}))

scatBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "scatr",
                name = "scat",
                version = c(1,0,0),
                options = options,
                results = scatResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Scatterplot
#'
#' Function for making clean, good looking scatter plots with the option to 
#' add marginal denisty or box plots.
#'
#' @examples
#' set.seed(1337)
#'
#' X <- rnorm(100)
#' Y <- 0.5*X + rnorm(100)
#' dat <- data.frame(X = X, Y = Y)
#'
#' scat(dat, x = 'X', y = 'Y', line = 'linear', se = TRUE, marg = 'dens')
#'
#' @param data the data as a data frame
#' @param x a string naming the variable from \code{data} that contains the  x
#'   coordinates of the points in the plot, variable must be numeric
#' @param y a string naming the variable from \code{data} that contains the  y
#'   coordinates of the points in the plot, variable must be numeric
#' @param group a string naming the variable from \code{data} that represents
#'   the  grouping variable
#' @param marg \code{none} (default), \code{dens}, or \code{box}, provide
#'   respectively no plots, density plots, or box plots on the axes
#' @param line \code{none} (default), \code{linear}, or \code{smooth}, provide
#'   respectively no regression line,  a linear regression line, or a smoothed
#'   regression line
#' @param se \code{TRUE} or \code{FALSE} (default), show the standard error
#'   for the regression line
#' @param xmin a number defining the minimum of the scale for the x-axis
#' @param xmax a number defining the maximum of the scale for the x-axis
#' @param xNBreaks a number defining the number of ticks breaks for the x-axis
#' @param xTitle a string (default: '') describing the title used for the
#'   x-axis
#' @param xTitleAlign \code{auto} (default), \code{left}, \code{middle}, or
#'   \code{right}, align the x-axis  title respectively automatically, to the
#'   left, middle, or right  side on the x-axis
#' @param xLabelsAngle a number from 0 to 90 defining the angle of the x-axis
#'   labels,  where 0 degrees represents completely horizontal labels.
#' @param ymin a number defining the minimum of the scale for the y-axis
#' @param ymax a number defining the maximum of the scale for the y-axis
#' @param yNBreaks a number defining the number of ticks breaks for the y-axis
#' @param yTitle a string (default: '') describing the title used for the
#'   y-axis
#' @param yTitleAlign \code{auto} (default), \code{top}, \code{middle}, or
#'   \code{bottom}, align the y-axis  title respectively automatically, to the
#'   top, middle, or bottom of  the y-axis
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$scat} \tab \tab \tab \tab \tab a scatter plot \cr
#' }
#'
#' @export
scat <- function(
    data,
    x,
    y,
    group = NULL,
    marg = "none",
    line = "none",
    se = FALSE,
    xmin = NULL,
    xmax = NULL,
    xNBreaks = NULL,
    xTitle = "",
    xTitleAlign = "auto",
    xLabelsAngle = NULL,
    ymin = NULL,
    ymax = NULL,
    yNBreaks = NULL,
    yTitle = "",
    yTitleAlign = "auto") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("scat requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- scatOptions$new(
        x = x,
        y = y,
        group = group,
        marg = marg,
        line = line,
        se = se,
        xmin = xmin,
        xmax = xmax,
        xNBreaks = xNBreaks,
        xTitle = xTitle,
        xTitleAlign = xTitleAlign,
        xLabelsAngle = xLabelsAngle,
        ymin = ymin,
        ymax = ymax,
        yNBreaks = yNBreaks,
        yTitle = yTitle,
        yTitleAlign = yTitleAlign)

    analysis <- scatClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

